### ISSUE TITLE
Listening is not enabled on port 58008

### ISSUE THREAD

**Issue by yutianqaq** [ttpreport/ligolo-mp#3]
Listening is not enabled on port 58008 for any precompiled binary. Tested on kali linux

<img width="1211" alt="PixPin_2024-03-17_23-36-50" src="https://github.com/ttpreport/ligolo-mp/assets/40353095/6fdbd304-4eef-4abe-b7a2-79f52141133f">

**Comment by ttpreport** [comment]
Did you start the daemon as well? It starts the actual RPC listener in daemon mode.

Interface to add operators is just a local cli tool that operates on sqlite database to generate/save required entries. (refer to setup step 2 in the readme).
