### ISSUE TITLE
Problems with setup and compilation

### ISSUE THREAD

**Issue by useragent23253** [ttpreport/ligolo-mp#4]
Hello, I've got some problem with setup. Tested env was debian 10, ubuntu, kali

./ligolo-mp_server_1.0.3_linux_amd64 
panic: could not initialize certificates: sql: no rows in result set

goroutine 1 [running]:
main.main()
        github.com/ttpreport/ligolo-mp/cmd/server/main.go:48 +0x7ab

Also was trying to compiled it but got errors like this

go: error loading module requirements
make: *** [Makefile:32: agent] Error 1

Any Suggestions? Thanks in advance

**Comment by ttpreport** [comment]
Looks like you have improperly provisioned db for some reason. Try removing `~/.ligolo-mp-server` and run the server again

**Comment by useragent23253** [comment]
Actually i don't understand what's going on here but just did like in you. I created daemon and executed ligolo-server. Tested on ubuntu 22
root@vps058:~/Desktop# service ligolo-mp status
● ligolo-mp.service - Ligolo-mp
     Loaded: loaded (/etc/systemd/system/ligolo-mp.service; disabled; vendor preset: enabled)
     Active: active (running) since Wed 2024-03-27 17:29:09 UTC; 3s ago
   Main PID: 718126 (ligolo-mp-serve)
      Tasks: 8 (limit: 4574)
     Memory: 182.4M
        CPU: 3.970s
     CGroup: /system.slice/ligolo-mp.service
             └─718126 /root/Desktop/ligolo-mp-server -daemon

Mar 27 13:29:09 vps112058.hostsailor.com systemd[1]: Started Ligolo-mp.
root@vps058:~/Desktop# ./ligolo-mp-server 

panic: could not initialize certificates: sql: no rows in result set

goroutine 1 [running]:
main.main()
        github.com/ttpreport/ligolo-mp/cmd/server/main.go:48 +0x7ab

**Comment by ttpreport** [comment]
So, when you first run the server (the service in your case), it initializes different stuff, including creating certificates and storing them in sqlite database. Based on what you've provided, it sounds like something went wrong during that process. 

Can you please provide output of `journalctl -u ligolo-mp`? I expect to see some errors in there that might lead us in the right direction.

**Comment by useragent23253** [comment]
Something with certificates i guess

`journalctl -u ligolo-mp
Mar 27 13:29:09 vps1120 systemd[1]: Started Ligolo-mp.
Mar 27 13:30:19 vps1120 ligolo-mp-server[718126]: panic: could not initialize certificates: sql: no rows in result set
Mar 27 13:30:19 vps1120 ligolo-mp-server[718126]: goroutine 1 [running]:
Mar 27 13:30:19 vps1120 ligolo-mp-server[718126]: main.main()
Mar 27 13:30:19 vps1120 ligolo-mp-server[718126]:         github.com/ttpreport/ligolo-mp/cmd/server/main.go:48 +0x7ab
Mar 27 13:30:19 vps1120 systemd[1]: ligolo-mp.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 27 13:30:19 vps1120 systemd[1]: ligolo-mp.service: Failed with result 'exit-code'.
Mar 27 13:30:19 vps1120 systemd[1]: ligolo-mp.service: Consumed 1min 11.204s CPU time.
Mar 27 13:30:22 vps1120 systemd[1]: ligolo-mp.service: Scheduled restart job, restart counter is at 1.
Mar 27 13:30:22 vps1120 systemd[1]: Stopped Ligolo-mp.
Mar 27 13:30:22 vps1120 systemd[1]: ligolo-mp.service: Consumed 1min 11.204s CPU time.`

**Comment by ttpreport** [comment]
@useragent23253 

Figured it out, it was indeed a bug, introduced in v1.0.2. Please, try v1.0.4 - should fix the issue.

I'll close this one for now, feel free to reopen if the issue persists.

**Comment by ttpreport** [comment]
@useragent23253 

Figured it out, it was indeed a bug, introduced in v1.0.2. Please, try v1.0.4 - should fix the issue.

I'll close this one for now, feel free to reopen if the issue persists.
